### ISSUE TITLE
Deploy fails with bower dependencies

### ISSUE THREAD

**Issue by jakeleboeuf** [oskarrough/ember-now-deployment-example#2]
I'm not able to deploy, and getting the following error- you ever seen this?

```
Error: Couldn't find /home/nowuser/src/dist/package.json. You may need to update your version of ember-cli-fastboot.
```

My package.json contains:
```
  "dependencies": {
    "ember-cli-fastboot": "^1.0.0-beta.15",
    "fastboot-app-server": "^1.0.0-rc.5"
  }
```

**Comment by oskarrough** [comment]
Can you share your scripts in `package.json` as well?

Also, when you deploy you should be able to follow along as `now` installs and starts your application in the cloud. It might say what is happening.

**Comment by oskarrough** [comment]
OK, it seems to fail whenever a bower dependency is installed. I only tested a clean Ember 2.11 which doesn't use bower...

**Comment by jakeleboeuf** [comment]
Yea, was just investigating the same thing- I tried a `postinstall: bower install` but that is obviously not going to work :-1:

For the time being, I can pull my bower deps into the build...

**Comment by oskarrough** [comment]
It was enough to add `bower install` to the `now-build` script.

Fixed by https://github.com/oskarrough/ember-now-deployment-example/commit/1edcb0b2196223cd3fa63f06aa57066e7d4ba9d1

**Comment by jakeleboeuf** [comment]
Man, still getting related errors: `sh: bower: not found`- is there something I need to do to install bower on my `now.sh` instance?

**Comment by jakeleboeuf** [comment]
`yarn add bower` fixes that one 👍

**Comment by oskarrough** [comment]
Great! But I'd like to know why :eyes: It works here without bower installed. What does `now -v` say? And do you have `engines > 7` in package.json?

**Comment by jakeleboeuf** [comment]
Looks like `bower` made its way into your `yarn.lock` file [@L534](https://github.com/oskarrough/ember-now-deployment-example/blob/master/yarn.lock#L534)?

`now -v` = `4.3.0`

**Comment by oskarrough** [comment]
You're right. Thank you! OK, adding `yarn add bower` to the readme.
